export const figmaSource = {
  fileKey: "FZhUp392NLvuTl611bidrx",
  pages: {
    screens: "268:1695",
    components: "268:1696",
    tokens: "291:717",
  },
  tokenCollections: {
    typography: "VariableCollectionId:192:993",
    colorFoundation: "VariableCollectionId:291:486",
    semantic: "VariableCollectionId:291:612",
    spacingRadius: "VariableCollectionId:291:695",
  },
  tokenExport: "src/design-system/figma-tokens.json",
  inspectedNodes: {
    button: "83:419",
    buttonPrimaryMedium: "83:269",
    buttonBorderMedium: "221:1206",
    buttonBuilder: "2:564",
    table: "339:2348",
    tableRowDefault: "331:532",
    badgeLive: "331:490",
    navigation: "217:1175",
    menuItem: "203:831",
    sidebar: "203:946",
    segmentsScreen: "240:2184",
    builderScreen: "8:9",
    pagination: "344:5289",
    dropdown: "149:456",
    dropdownOption: "149:478",
    textField: "212:852",
    textarea: "291:1544",
  },
} as const;

export const cssVariables = {
  foundation: {
    gray: {
      50: "var(--gray-50)",
      100: "var(--gray-100)",
      200: "var(--gray-200)",
      300: "var(--gray-300)",
      400: "var(--gray-400)",
      500: "var(--gray-500)",
      600: "var(--gray-600)",
      700: "var(--gray-700)",
      800: "var(--gray-800)",
      900: "var(--gray-900)",
      950: "var(--gray-950)",
    },
    violet: {
      50: "var(--violet-50)",
      100: "var(--violet-100)",
      200: "var(--violet-200)",
      300: "var(--violet-300)",
      400: "var(--violet-400)",
      500: "var(--violet-500)",
      600: "var(--violet-600)",
      700: "var(--violet-700)",
      800: "var(--violet-800)",
      900: "var(--violet-900)",
      950: "var(--violet-950)",
    },
  },
  semantic: {
    background: {
      page: "var(--background-page)",
      default: "var(--background-default)",
      subtle: "var(--background-subtle)",
      muted: "var(--background-muted)",
      inverse: "var(--background-inverse)",
      brand: "var(--background-brand)",
      brandSubtle: "var(--background-brand-subtle)",
      overlay: "var(--background-overlay)",
    },
    text: {
      default: "var(--text-default)",
      secondary: "var(--text-secondary)",
      subtle: "var(--text-subtle)",
      disabled: "var(--text-disabled)",
      inverse: "var(--text-inverse)",
      brand: "var(--text-brand)",
      error: "var(--text-error)",
      success: "var(--text-success)",
      warning: "var(--text-warning)",
      info: "var(--text-info)",
      base: "var(--text-base)",
    },
    border: {
      default: "var(--border-default)",
      strong: "var(--border-strong)",
      subtle: "var(--border-subtle)",
      focus: "var(--border-focus)",
      error: "var(--border-error)",
      brand: "var(--border-brand)",
    },
    icon: {
      default: "var(--icon-default)",
      subtle: "var(--icon-subtle)",
      disabled: "var(--icon-disabled)",
      brand: "var(--icon-brand)",
      error: "var(--icon-error)",
      success: "var(--icon-success)",
      warning: "var(--icon-warning)",
      inverse: "var(--icon-inverse)",
    },
    action: {
      primaryBg: "var(--action-primary-bg)",
      primaryHover: "var(--action-primary-hover)",
      primaryPressed: "var(--action-primary-pressed)",
      primaryDisabled: "var(--action-primary-disabled)",
      primaryText: "var(--action-primary-text)",
      secondaryBg: "var(--action-secondary-bg)",
      secondaryHover: "var(--action-secondary-hover)",
      secondaryPressed: "var(--action-secondary-pressed)",
      secondaryBorder: "var(--action-secondary-border)",
      secondaryText: "var(--action-secondary-text)",
      ghostHover: "var(--action-ghost-hover)",
      ghostPressed: "var(--action-ghost-pressed)",
      ghostText: "var(--action-ghost-text)",
      softBg: "var(--action-soft-bg)",
      softHover: "var(--action-soft-hover)",
      softPressed: "var(--action-soft-pressed)",
      softText: "var(--action-soft-text)",
      dangerBg: "var(--action-danger-bg)",
      dangerHover: "var(--action-danger-hover)",
      dangerPressed: "var(--action-danger-pressed)",
      dangerText: "var(--action-danger-text)",
    },
    feedback: {
      errorBg: "var(--feedback-error-bg)",
      errorBorder: "var(--feedback-error-border)",
      errorText: "var(--feedback-error-text)",
      errorIcon: "var(--feedback-error-icon)",
      successBg: "var(--feedback-success-bg)",
      successBorder: "var(--feedback-success-border)",
      successText: "var(--feedback-success-text)",
      successIcon: "var(--feedback-success-icon)",
      warningBg: "var(--feedback-warning-bg)",
      warningBorder: "var(--feedback-warning-border)",
      warningText: "var(--feedback-warning-text)",
      warningIcon: "var(--feedback-warning-icon)",
      infoBg: "var(--feedback-info-bg)",
      infoBorder: "var(--feedback-info-border)",
      infoText: "var(--feedback-info-text)",
      infoIcon: "var(--feedback-info-icon)",
      brandBg: "var(--feedback-brand-bg)",
      brandBorder: "var(--feedback-brand-border)",
      brandText: "var(--feedback-brand-text)",
      brandIcon: "var(--feedback-brand-icon)",
      neutralBg: "var(--feedback-neutral-bg)",
      neutralBorder: "var(--feedback-neutral-border)",
      neutralText: "var(--feedback-neutral-text)",
    },
    surface: {
      default: "var(--surface-default)",
      raised: "var(--surface-raised)",
      overlay: "var(--surface-overlay)",
      sunken: "var(--surface-sunken)",
      brand: "var(--surface-brand)",
      dark: "var(--surface-dark)",
      darkCard: "var(--surface-dark-card)",
    },
    sidebar: {
      bg: "var(--sidebar-bg)",
      bgActive: "var(--sidebar-bg-active)",
      bgHover: "var(--sidebar-bg-hover)",
      text: "var(--sidebar-text)",
      textActive: "var(--sidebar-text-active)",
      textBrand: "var(--sidebar-text-brand)",
      border: "var(--sidebar-border)",
      icon: "var(--sidebar-icon)",
      iconActive: "var(--sidebar-icon-active)",
      iconBrand: "var(--sidebar-icon-brand)",
      badgeBg: "var(--sidebar-badge-bg)",
    },
  },
} as const;

export const tokens = {
  color: {
    background: {
      app: "var(--ads-app-bg)",
      page: cssVariables.semantic.background.page,
      default: cssVariables.semantic.background.default,
      muted: cssVariables.semantic.background.muted,
      brand: cssVariables.semantic.background.brand,
      brandSubtle: cssVariables.semantic.background.brandSubtle,
    },
    surface: {
      default: cssVariables.semantic.surface.default,
      subtle: cssVariables.semantic.surface.sunken,
      raised: cssVariables.semantic.surface.raised,
      dark: cssVariables.semantic.surface.dark,
      darkCard: cssVariables.semantic.surface.darkCard,
      sidebar: cssVariables.semantic.sidebar.bg,
      sidebarActive: cssVariables.semantic.sidebar.bgActive,
    },
    text: cssVariables.semantic.text,
    icon: cssVariables.semantic.icon,
    border: cssVariables.semantic.border,
    action: {
      primaryBg: cssVariables.semantic.action.primaryBg,
      primaryBgHover: cssVariables.semantic.action.primaryHover,
      primaryBgPress: cssVariables.semantic.action.primaryPressed,
      primaryText: cssVariables.semantic.action.primaryText,
      borderStroke: "var(--action-border-stroke)",
      borderText: "var(--action-border-text)",
      ghostText: cssVariables.semantic.action.ghostText,
      ghostHover: cssVariables.semantic.action.ghostHover,
      softBg: cssVariables.semantic.action.softBg,
      softText: cssVariables.semantic.action.softText,
      dangerBg: cssVariables.semantic.action.dangerBg,
      dangerText: cssVariables.semantic.action.dangerText,
    },
    status: {
      live: "var(--status-live)",
      active: "var(--status-active)",
      ended: "var(--status-ended)",
      draft: "var(--status-draft)",
      scheduled: "var(--status-scheduled)",
      highlight: "var(--status-highlight)",
    },
    feedback: cssVariables.semantic.feedback,
  },
  spacing: {
    0: "var(--spacing-0)",
    0.25: "var(--spacing-0_25)",
    0.5: "var(--spacing-0_5)",
    0.75: "var(--spacing-0_75)",
    1: "var(--spacing-1)",
    1.5: "var(--spacing-1_5)",
    1.75: "var(--spacing-1_75)",
    2: "var(--spacing-2)",
    2.5: "var(--spacing-2_5)",
    3: "var(--spacing-3)",
    3.5: "var(--spacing-3_5)",
    4: "var(--spacing-4)",
    5: "var(--spacing-5)",
    6: "var(--spacing-6)",
    7: "var(--spacing-7)",
    8: "var(--spacing-8)",
    10: "var(--spacing-10)",
    12: "var(--spacing-12)",
    14: "var(--spacing-14)",
    16: "var(--spacing-16)",
    20: "var(--spacing-20)",
    24: "var(--spacing-24)",
  },
  radius: {
    none: "var(--radius-none)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    pill: "var(--radius-99)",
    full: "var(--radius-full)",
  },
  type: {
    family: "var(--font-family)",
    size: {
      10: "var(--font-size-10)",
      11: "var(--font-size-11)",
      12: "var(--font-size-12)",
      13: "var(--font-size-13)",
      14: "var(--font-size-14)",
      15: "var(--font-size-15)",
      16: "var(--font-size-16)",
      18: "var(--font-size-18)",
      20: "var(--font-size-20)",
      22: "var(--font-size-22)",
      24: "var(--font-size-24)",
      28: "var(--font-size-28)",
    },
    weight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
      extrabold: "var(--font-weight-extrabold)",
      black: "var(--font-weight-black)",
    },
    lineHeight: {
      12: "var(--line-height-12)",
      16: "var(--line-height-16)",
      20: "var(--line-height-20)",
      24: "var(--line-height-24)",
      28: "var(--line-height-28)",
      32: "var(--line-height-32)",
      36: "var(--line-height-36)",
      40: "var(--line-height-40)",
      44: "var(--line-height-44)",
      48: "var(--line-height-48)",
    },
  },
  shadow: {
    actionPrimary: "var(--shadow-action-primary)",
    hover: "var(--shadow-hover)",
    control: "var(--shadow-control)",
    card: "var(--shadow-card)",
    insetAction: "var(--shadow-inset-action)",
  },
} as const;

export type DesignTokens = typeof tokens;
